/* Lift and Coast — front-end logic. Reads window.LAC_DATA (generated by
   pipeline/export_web.py). No framework, no build step. */
(function () {
  "use strict";
  var DATA = window.LAC_DATA;
  if (!DATA) { document.body.innerHTML = "<p style='padding:40px;font-family:monospace'>data.js failed to load — run <code>python3 pipeline/export_web.py</code>.</p>"; return; }

  var seasons = DATA.seasons;
  var byYear = {};
  seasons.forEach(function (s) { byYear[s.year] = s; });
  var years = seasons.map(function (s) { return s.year; });

  var $ = function (id) { return document.getElementById(id); };
  var el = function (tag, cls, html) {
    var e = document.createElement(tag);
    if (cls) e.className = cls;
    if (html != null) e.innerHTML = html;
    return e;
  };
  var fmt = function (n) {
    // tidy number: drop trailing .0
    return (Math.round(n * 10) / 10).toString().replace(/\.0$/, "");
  };
  var esc = function (s) { return String(s).replace(/[&<>]/g, function (c) {
    return { "&": "&amp;", "<": "&lt;", ">": "&gt;" }[c]; }); };

  /* ---- stat tower -------------------------------------------------------- */
  function tower() {
    var t = DATA.meta.totals;
    var cells = [
      [t.seasons, "seasons"],
      [t.races.toLocaleString(), "grands prix"],
      [t.drivers, "drivers"],
      [t.finaleTitles, "to the final race"],
      [t.scoringSensitive, "scoring-sensitive"],
      [t.tieSeasons, "tie under a system"],
    ];
    var host = $("tower"); host.innerHTML = "";
    cells.forEach(function (c) {
      var cell = el("div", "cell");
      cell.appendChild(el("div", "t-num num", c[0]));
      cell.appendChild(el("div", "t-lab", c[1]));
      host.appendChild(cell);
    });
  }

  /* ---- flags ------------------------------------------------------------- */
  function flags(s) {
    var host = $("flags"); host.innerHTML = "";
    if (s.clinch.wentToFinale) host.appendChild(el("span", "flag wire", "went to the wire"));
    else if (s.clinch.racesRemaining >= 3) host.appendChild(el("span", "flag domin", "clinched +" + s.clinch.racesRemaining));
    if (s.teammate.outQualified || s.teammate.outRaced) host.appendChild(el("span", "flag anom", "beaten by teammate"));
    if (s.anyChange) host.appendChild(el("span", "flag scoring", "scoring-sensitive"));
  }

  /* ---- champion ---------------------------------------------------------- */
  function champion(s) {
    var b = $("champ-body"); b.innerHTML = "";
    b.appendChild(el("div", "champ-name", esc(s.champion)));
    b.appendChild(el("div", "champ-team", esc(s.constructor)));
    var stats = el("div", "champ-stats");
    [[fmt(s.points), "points"], [s.wins, "wins"], [s.clinch.totalRounds, "rounds"]].forEach(function (x) {
      var st = el("div", "stat");
      st.appendChild(el("div", "s-num num", x[0]));
      st.appendChild(el("div", "s-lab", x[1]));
      stats.appendChild(st);
    });
    b.appendChild(stats);
  }

  /* ---- clinch geometry --------------------------------------------------- */
  function clinch(s) {
    var c = s.clinch, b = $("clinch-body"); b.innerHTML = "";
    var line = el("div", "clinch-line");
    line.appendChild(el("span", "clinch-round num", "R" + c.round));
    line.appendChild(el("span", "clinch-race", esc(c.race || "")));
    b.appendChild(line);
    b.appendChild(el("div", "clinch-meta",
      c.wentToFinale
        ? "decided at the final round — mathematically open until the flag"
        : "secured with <b style='color:var(--t-green)'>" + c.racesRemaining + "</b> race" + (c.racesRemaining === 1 ? "" : "s") + " still to run"));

    var bar = el("div", "racebar");
    for (var r = 1; r <= c.totalRounds; r++) {
      var cls = r < c.round ? "rb run" : (r === c.round ? "rb clinch" : "rb after");
      var seg = el("div", cls);
      seg.title = "Round " + r + (r === c.round ? " — clinched" : "");
      bar.appendChild(seg);
    }
    b.appendChild(bar);
    b.appendChild(el("div", "clinch-margin",
      "closest the lead ever got: <b>" + fmt(c.closestMargin) + "</b> pts between P1 and P2"));
  }

  /* ---- points-system invariance ----------------------------------------- */
  function invariance(s) {
    var b = $("inv-body"); b.innerHTML = "";
    var table = el("table", "inv-table");
    table.innerHTML = "<thead><tr><th>scoring system</th><th>champion</th><th class='inv-pts'>pts</th></tr></thead>";
    var tb = el("tbody");
    s.invariance.forEach(function (i) {
      var tr = el("tr");
      tr.appendChild(el("td", "inv-sys", esc(i.table) + (i.own ? " <span style='color:var(--amber)' title='the era\\'s real table'>&#9666;era</span>" : "")));
      var who = el("td", "inv-who " + (i.tie ? "tie" : (i.changes ? "flip" : "held")));
      if (i.tie) {
        who.innerHTML = esc(i.champ.replace(/^TIE:\s*/, "")) + "<span class='inv-tag tie'>tie</span>";
      } else if (i.changes) {
        who.innerHTML = esc(i.champ) + "<span class='inv-tag flip'>flip</span>";
      } else {
        who.textContent = i.champ;
      }
      tr.appendChild(who);
      tr.appendChild(el("td", "inv-pts num", fmt(i.pts)));
      tb.appendChild(tr);
    });
    table.appendChild(tb); b.appendChild(table);

    var foot = "Real champion under the era's actual rules (table, fastest lap <i>and</i> any dropped-scores rule): <b style='color:var(--t-green)'>" +
      esc(s.champion) + "</b>. Each row above applies one table's position points to the real finishing order, with all results counting and no fastest-lap point. ";
    if (s.flips.length) foot += "Some tables would crown <b style='color:var(--amber)'>" + esc(s.flips.join(", ")) + "</b> outright. ";
    if (s.hasTie) foot += "Some tables tie at the top — shown as a tie; the era's countback tie-break (wins, then places) is noted, not recomputed. ";
    if (!s.flips.length && !s.hasTie) foot += "The title is invariant to the scoring table.";
    b.appendChild(el("div", "inv-foot", foot));
  }

  /* ---- teammate H2H ------------------------------------------------------ */
  function h2hBar(meWins, themWins, races) {
    var bar = el("div", "h2h-bar");
    var ties = Math.max(0, races - meWins - themWins);
    var total = Math.max(1, meWins + themWins + ties);
    function seg(cls, n) {
      if (n <= 0) return;
      var s = el("div", "h2h-seg " + cls, String(n));
      s.style.flex = n + " 0 0"; bar.appendChild(s);
    }
    seg("win", meWins); seg("tie", ties); seg("lose", themWins);
    return bar;
  }

  function teammate(s) {
    var t = s.teammate, b = $("tm-body"); b.innerHTML = "";
    // names header
    var names = el("div", "h2h-names");
    names.appendChild(el("span", "me", esc(s.champion.split(" ").slice(-1)[0]) + " (champ)"));
    names.appendChild(el("span", "them", esc(t.names || "—")));
    b.appendChild(names);

    // qualifying
    var q = el("div", "h2h-row");
    q.appendChild(el("div", "h2h-head", "<span>qualifying h2h</span><span>" +
      (t.qualiAvailable ? t.qWins + "&ndash;" + t.qLosses : "n/a") + "</span>"));
    if (t.qualiAvailable) q.appendChild(h2hBar(t.qWins, t.qLosses, t.qRaces));
    else q.appendChild(el("div", "tm-note", "no qualifying-time data before 1994 — race h2h only"));
    b.appendChild(q);

    // race
    var r = el("div", "h2h-row");
    r.appendChild(el("div", "h2h-head", "<span>race h2h <span style='color:var(--ink-dim)'>(both classified)</span></span><span>" +
      t.rWins + "&ndash;" + t.rLosses + "</span>"));
    r.appendChild(h2hBar(t.rWins, t.rLosses, t.rRaces));
    b.appendChild(r);

    // points within pairing
    b.appendChild(el("div", "tm-points",
      "head-to-head points &nbsp; <b>" + fmt(t.champPoints) + "</b> <span style='color:var(--ink-dim)'>champ</span> &nbsp;vs&nbsp; <b>" + fmt(t.tmPoints) + "</b> <span style='color:var(--ink-dim)'>teammate</span>"));

    // anomaly callout
    if (t.outQualified || t.outRaced) {
      var what = [];
      if (t.outQualified) what.push("out-qualified " + t.qLosses + "&ndash;" + t.qWins);
      if (t.outRaced) what.push("out-raced " + t.rLosses + "&ndash;" + t.rWins);
      b.appendChild(el("div", "anomaly", "&#9650; ANOMALY — champion " + what.join(" and ") + " by their own teammate"));
    }
  }

  /* ---- render ------------------------------------------------------------ */
  function render(year) {
    var s = byYear[year];
    if (!s) return;
    $("season").value = year;
    $("ro-gap").textContent = "Δ " + fmt(s.clinch.closestMargin) + " pts";
    flags(s); champion(s); clinch(s); invariance(s); teammate(s);
    try { if (history.replaceState) history.replaceState(null, "", "#" + year); } catch (e) {}
  }

  /* ---- wiring ------------------------------------------------------------ */
  function init() {
    tower();
    var sel = $("season");
    years.slice().reverse().forEach(function (y) {
      sel.appendChild(el("option", null, y)).value = y;
    });
    sel.addEventListener("change", function () { render(+sel.value); });
    $("prev").addEventListener("click", function () {
      var i = years.indexOf(+sel.value); if (i > 0) render(years[i - 1]);
    });
    $("next").addEventListener("click", function () {
      var i = years.indexOf(+sel.value); if (i < years.length - 1) render(years[i + 1]);
    });
    document.addEventListener("keydown", function (e) {
      if (e.key === "ArrowLeft") $("prev").click();
      if (e.key === "ArrowRight") $("next").click();
    });
    var hash = parseInt(location.hash.replace("#", ""), 10);
    render(byYear[hash] ? hash : 2008);  // default: 2008 — the last-corner title
  }

  init();
})();
