/* Lift and Coast — front-end logic. Reads window.LAC_DATA (generated by
   pipeline/export_web.py). No framework, no build step.

   Routes (hash-based):
     #/                 season dossier (default season)
     #/s/<year>         season dossier for <year>   (deep-link target from lists)
     #<year>            legacy alias for #/s/<year>
     #/beaten           cross-season: champions beaten by their teammate
     #/scoring          cross-season: scoring-sensitive titles (flips + ties, distinct)
     #/finals           cross-season: final-race deciders
     #/clinch           cross-season: earliest title clinches
*/
(function () {
  "use strict";
  var DATA = window.LAC_DATA;
  if (!DATA) { document.body.innerHTML = "<p style='padding:40px;font-family:monospace'>data.js failed to load — run <code>python3 pipeline/export_web.py</code>.</p>"; return; }

  var seasons = DATA.seasons;
  var byYear = {};
  seasons.forEach(function (s) { byYear[s.year] = s; });
  var years = seasons.map(function (s) { return s.year; });

  var $ = function (id) { return document.getElementById(id); };
  var el = function (tag, cls, html) {
    var e = document.createElement(tag);
    if (cls) e.className = cls;
    if (html != null) e.innerHTML = html;
    return e;
  };
  var fmt = function (n) {
    return (Math.round(n * 10) / 10).toString().replace(/\.0$/, "");
  };
  var esc = function (s) { return String(s == null ? "" : s).replace(/[&<>]/g, function (c) {
    return { "&": "&amp;", "<": "&lt;", ">": "&gt;" }[c]; }); };
  var last = function (name) { return String(name || "").split(" ").slice(-1)[0]; };

  /* ---- Phase D pace-delta helpers (shared dossier + pace view) ----------- */
  var TIER_T = { 1: "same session / track / car — fully comparable",
                 2: "same race / car, clean-lap method — mostly comparable, caveated",
                 3: "cross-era / context — contextual only" };
  function tierChip(t) {
    return "<span class='tier tier" + t + "' title='Tier " + t + " — " + TIER_T[t] + "'>T" + t + "</span>";
  }
  // signed gap from a perspective: negative => the perspective driver is faster.
  // returns {fast, slow, abs} where fast/slow are 'me'|'them'
  function orient(median) {
    return median < 0 ? { fast: "me", slow: "them", abs: -median }
                      : { fast: "them", slow: "me", abs: median };
  }
  function deltaNum(absVal, unit) {
    return "<span class='delta num'>&minus;" + absVal.toFixed(3) + unit + "</span>";
  }
  // one pace row: champCode/tmCode are display codes; median is champion-perspective
  function paceRow(label, tier, champCode, tmCode, median, unit, sub, weak) {
    var o = orient(median);
    var fastCode = o.fast === "me" ? champCode : tmCode;
    var slowCode = o.fast === "me" ? tmCode : champCode;
    var dn = "<span class='delta num" + (weak ? " delta-weak" : "") + "'>&minus;" + o.abs.toFixed(3) + unit + "</span>";
    var row = el("div", "pace-row");
    row.innerHTML =
      "<div class='pace-label'>" + label + " " + tierChip(tier) + (weak ? " <span class='rel rel-low'>small n</span>" : "") + "</div>" +
      "<div class='pace-val'><span class='pc-fast'>" + esc(fastCode) + "</span> " +
        dn + " <span class='pc-slow'>vs " + esc(slowCode) + "</span></div>" +
      "<div class='pace-sub'>" + sub + "</div>";
    return row;
  }
  function paceBlock(s) {
    var wrap = el("div", "tm-pace");
    wrap.appendChild(el("div", "tm-pace-h", "MEASURED PACE DELTAS <span class='tm-pace-src'>Phase D &middot; same car</span>"));
    var d = s.teammate.delta;
    var champ = s.code || last(s.champion).slice(0, 3).toUpperCase();
    // QUALIFYING (Tier 1)
    if (d && d.quali) {
      var tm = d.vsCode || last(d.vs).slice(0, 3).toUpperCase();
      wrap.appendChild(paceRow("QUALIFYING", 1, champ, tm, d.quali.median, "s",
        "median over n=" + d.quali.n + " of " + d.quali.races + " comparison races" +
        (d.multiple ? " &middot; primary teammate" : "")));
    } else {
      wrap.appendChild(el("div", "pace-row pace-na",
        "<div class='pace-label'>QUALIFYING " + tierChip(1) + "</div>" +
        "<div class='pace-na-txt'>" + (s.year < 1994 ? "no qualifying-time data before 1994 — race H2H only"
                                                       : "no comparable qualifying delta") + "</div>"));
    }
    // RACE PACE (Tier 2)
    if (d && d.race) {
      var tm2 = d.vsCode || last(d.vs).slice(0, 3).toUpperCase();
      if (d.race.median === null) {
        wrap.appendChild(el("div", "pace-row pace-na",
          "<div class='pace-label'>RACE PACE " + tierChip(2) + " <span class='rel rel-low'>low</span></div>" +
          "<div class='pace-na-txt'>no reliable comparison &middot; " + d.race.nLow +
          " race" + (d.race.nLow === 1 ? "" : "s") + " flagged low-reliability</div>"));
      } else {
        var weak = d.race.nOk < 3;
        var sub = "<span class='rel " + (weak ? "rel-low" : "rel-ok") + "'>" + d.race.nOk +
                  " reliable race" + (d.race.nOk === 1 ? "" : "s") + "</span>";
        if (d.race.nLow) sub += " &middot; <span class='rel rel-low'>" + d.race.nLow + " flagged low</span> (excluded)";
        wrap.appendChild(paceRow("RACE PACE", 2, champ, tm2, d.race.median, "s/lap", sub, weak));
      }
    } else {
      wrap.appendChild(el("div", "pace-row pace-na",
        "<div class='pace-label'>RACE PACE " + tierChip(2) + "</div>" +
        "<div class='pace-na-txt'>" + (s.year < 1996 ? "no lap-time data before 1996" : "no clean-lap comparison") + "</div>"));
    }
    return wrap;
  }

  /* ====================================================================== */
  /*  STAT TOWER (shared header)                                            */
  /* ====================================================================== */
  function tower() {
    var t = DATA.meta.totals;
    var cells = [
      [t.seasons, "seasons", null],
      [t.races.toLocaleString(), "grands prix", null],
      [t.drivers, "drivers", null],
      [t.finaleTitles, "to the final race", "#/finals"],
      [t.scoringSensitive, "scoring-sensitive", "#/scoring"],
      [t.tieSeasons, "tie under a system", "#/scoring"],
    ];
    var host = $("tower"); host.innerHTML = "";
    cells.forEach(function (c) {
      var cell = el(c[2] ? "a" : "div", "cell" + (c[2] ? " cell-link" : ""));
      if (c[2]) { cell.href = c[2]; }
      cell.appendChild(el("div", "t-num num", c[0]));
      cell.appendChild(el("div", "t-lab", c[1]));
      host.appendChild(cell);
    });
  }

  /* ====================================================================== */
  /*  SEASON DOSSIER                                                        */
  /* ====================================================================== */
  function flags(s) {
    var host = $("flags"); host.innerHTML = "";
    if (s.clinch.wentToFinale) host.appendChild(el("span", "flag wire", "went to the wire"));
    else if (s.clinch.racesRemaining >= 3) host.appendChild(el("span", "flag domin", "clinched +" + s.clinch.racesRemaining));
    if (s.teammate.outQualified || s.teammate.outRaced) host.appendChild(el("span", "flag anom", "beaten by teammate"));
    if (s.anyChange) host.appendChild(el("span", "flag scoring", "scoring-sensitive"));
  }

  function champion(s) {
    var b = $("champ-body"); b.innerHTML = "";
    b.appendChild(el("div", "champ-name", esc(s.champion)));
    b.appendChild(el("div", "champ-team", esc(s.constructor)));
    var stats = el("div", "champ-stats");
    [[fmt(s.points), "points"], [s.wins, "wins"], [s.clinch.totalRounds, "rounds"]].forEach(function (x) {
      var st = el("div", "stat");
      st.appendChild(el("div", "s-num num", x[0]));
      st.appendChild(el("div", "s-lab", x[1]));
      stats.appendChild(st);
    });
    b.appendChild(stats);
  }

  function clinch(s) {
    var c = s.clinch, b = $("clinch-body"); b.innerHTML = "";
    var line = el("div", "clinch-line");
    line.appendChild(el("span", "clinch-round num", "R" + c.round));
    line.appendChild(el("span", "clinch-race", esc(c.race || "")));
    b.appendChild(line);
    b.appendChild(el("div", "clinch-meta",
      c.wentToFinale
        ? "decided at the final round — mathematically open until the flag"
        : "secured with <b style='color:var(--t-green)'>" + c.racesRemaining + "</b> race" + (c.racesRemaining === 1 ? "" : "s") + " still to run"));
    var bar = el("div", "racebar");
    for (var r = 1; r <= c.totalRounds; r++) {
      var cls = r < c.round ? "rb run" : (r === c.round ? "rb clinch" : "rb after");
      var seg = el("div", cls);
      seg.title = "Round " + r + (r === c.round ? " — clinched" : "");
      bar.appendChild(seg);
    }
    b.appendChild(bar);
    b.appendChild(el("div", "clinch-margin",
      "closest the lead ever got: <b>" + fmt(c.closestMargin) + "</b> pts between P1 and P2"));
  }

  function invariance(s) {
    var b = $("inv-body"); b.innerHTML = "";
    var table = el("table", "inv-table");
    table.innerHTML = "<thead><tr><th>scoring system</th><th>champion</th><th class='inv-pts'>pts</th></tr></thead>";
    var tb = el("tbody");
    s.invariance.forEach(function (i) {
      var tr = el("tr");
      tr.appendChild(el("td", "inv-sys", esc(i.table) + (i.own ? " <span style='color:var(--amber)' title='the era\\'s real table'>&#9666;era</span>" : "")));
      var who = el("td", "inv-who " + (i.tie ? "tie" : (i.changes ? "flip" : "held")));
      if (i.tie) {
        who.innerHTML = esc(i.champ.replace(/^TIE:\s*/, "")) + "<span class='inv-tag tie'>tie</span>";
      } else if (i.changes) {
        who.innerHTML = esc(i.champ) + "<span class='inv-tag flip'>flip</span>";
      } else {
        who.textContent = i.champ;
      }
      tr.appendChild(who);
      tr.appendChild(el("td", "inv-pts num", fmt(i.pts)));
      tb.appendChild(tr);
    });
    table.appendChild(tb); b.appendChild(table);
    var foot = "Real champion under the era's actual rules (table, fastest lap <i>and</i> any dropped-scores rule): <b style='color:var(--t-green)'>" +
      esc(s.champion) + "</b>. Each row above applies one table's position points to the real finishing order, with all results counting and no fastest-lap point. ";
    if (s.flips.length) foot += "Some tables would crown <b style='color:var(--amber)'>" + esc(s.flips.join(", ")) + "</b> outright. ";
    if (s.hasTie) foot += "Some tables tie at the top — shown as a tie; the era's countback tie-break (wins, then places) is noted, not recomputed. ";
    if (!s.flips.length && !s.hasTie) foot += "The title is invariant to the scoring table.";
    b.appendChild(el("div", "inv-foot", foot));
  }

  function h2hBar(meWins, themWins, races) {
    var bar = el("div", "h2h-bar");
    var ties = Math.max(0, races - meWins - themWins);
    function seg(cls, n) {
      if (n <= 0) return;
      var s = el("div", "h2h-seg " + cls, String(n));
      s.style.flex = n + " 0 0"; bar.appendChild(s);
    }
    seg("win", meWins); seg("tie", ties); seg("lose", themWins);
    return bar;
  }

  function teammate(s) {
    var t = s.teammate, b = $("tm-body"); b.innerHTML = "";
    var names = el("div", "h2h-names");
    names.appendChild(el("span", "me", esc(last(s.champion)) + " (champ)"));
    names.appendChild(el("span", "them", esc(t.names || "—")));
    b.appendChild(names);
    var q = el("div", "h2h-row");
    q.appendChild(el("div", "h2h-head", "<span>qualifying h2h</span><span>" +
      (t.qualiAvailable ? t.qWins + "&ndash;" + t.qLosses : "n/a") + "</span>"));
    if (t.qualiAvailable) q.appendChild(h2hBar(t.qWins, t.qLosses, t.qRaces));
    else q.appendChild(el("div", "tm-note", "no qualifying-time data before 1994 — race h2h only"));
    b.appendChild(q);
    var r = el("div", "h2h-row");
    r.appendChild(el("div", "h2h-head", "<span>race h2h <span style='color:var(--ink-dim)'>(both classified)</span></span><span>" +
      t.rWins + "&ndash;" + t.rLosses + "</span>"));
    r.appendChild(h2hBar(t.rWins, t.rLosses, t.rRaces));
    b.appendChild(r);
    b.appendChild(el("div", "tm-points",
      "head-to-head points &nbsp; <b>" + fmt(t.champPoints) + "</b> <span style='color:var(--ink-dim)'>champ</span> &nbsp;vs&nbsp; <b>" + fmt(t.tmPoints) + "</b> <span style='color:var(--ink-dim)'>teammate</span>"));
    b.appendChild(paceBlock(s));
    if (t.outQualified || t.outRaced) {
      var what = [];
      if (t.outQualified) what.push("out-qualified " + t.qLosses + "&ndash;" + t.qWins);
      if (t.outRaced) what.push("out-raced " + t.rLosses + "&ndash;" + t.rWins);
      b.appendChild(el("div", "anomaly", "&#9650; ANOMALY — champion " + what.join(" and ") + " by their own teammate"));
    }
  }

  function renderSeason(year) {
    var s = byYear[year] || byYear[2008];
    $("season").value = s.year;
    $("ro-gap").textContent = "Δ " + fmt(s.clinch.closestMargin) + " pts";
    flags(s); champion(s); clinch(s); invariance(s); teammate(s);
  }

  /* ====================================================================== */
  /*  CROSS-SEASON LIST VIEWS                                               */
  /* ====================================================================== */
  // a head-to-head score like "12–8" with winner side coloured (purple) / loser (yellow)
  function score(aWins, bWins, swap) {
    var aCls = aWins > bWins ? "sc-win" : (aWins < bWins ? "sc-lose" : "sc-tie");
    var bCls = bWins > aWins ? "sc-win" : (bWins < aWins ? "sc-lose" : "sc-tie");
    return "<span class='sc'><span class='" + aCls + "'>" + aWins + "</span>" +
           "<span class='sc-dash'>&ndash;</span><span class='" + bCls + "'>" + bWins + "</span></span>";
  }
  function rowLink(tr, year) {
    tr.className = (tr.className + " lt-row").trim();
    tr.tabIndex = 0;
    tr.setAttribute("role", "link");
    tr.title = "open " + year + " dossier";
    var go = function () { location.hash = "#/s/" + year; };
    tr.addEventListener("click", go);
    tr.addEventListener("keydown", function (e) { if (e.key === "Enter") go(); });
    return tr;
  }
  function ltable(cols) {
    var t = el("table", "lt");
    var thead = "<thead><tr>";
    cols.forEach(function (c) { thead += "<th class='" + (c.cls || "") + "'>" + c.h + "</th>"; });
    t.innerHTML = thead + "</tr></thead>";
    t.appendChild(el("tbody"));
    return t;
  }
  function yearCell(y) { return "<td class='lt-year num'>" + y + "</td>"; }

  // 1) champions beaten by their teammate ---------------------------------
  function renderBeaten() {
    var rows = seasons.filter(function (s) { return s.teammate.outQualified || s.teammate.outRaced; });
    rows.sort(function (a, b) {
      var sev = function (s) {
        return (s.teammate.outQualified ? s.teammate.qLosses - s.teammate.qWins : 0) +
               (s.teammate.outRaced ? s.teammate.rLosses - s.teammate.rWins : 0);
      };
      return sev(b) - sev(a) || b.year - a.year;
    });
    var host = el("div");
    var t = ltable([
      { h: "season", cls: "lt-year" }, { h: "champion" }, { h: "teammate" },
      { h: "quali h2h", cls: "lt-r" }, { h: "race h2h", cls: "lt-r" }, { h: "", cls: "lt-tag" },
    ]);
    var tb = t.querySelector("tbody");
    rows.forEach(function (s) {
      var tm = s.teammate;
      var tag = (tm.outQualified && tm.outRaced) ? "both" : (tm.outQualified ? "out-qualified" : "out-raced");
      var quali = tm.qualiAvailable
        ? score(tm.qWins, tm.qLosses)
        : "<span class='lt-na'>&mdash; <span class='lt-na-sub'>race only</span></span>";
      var tr = el("tr");
      tr.innerHTML = yearCell(s.year) +
        "<td class='lt-name'>" + esc(s.champion) + "</td>" +
        "<td class='lt-name lt-them'>" + esc(tm.names || "—") + "</td>" +
        "<td class='lt-r'>" + quali + "</td>" +
        "<td class='lt-r'>" + score(tm.rWins, tm.rLosses) + "</td>" +
        "<td class='lt-tag'><span class='tg tg-anom'>" + tag + "</span></td>";
      tb.appendChild(rowLink(tr, s.year));
    });
    host.appendChild(t);
    host.appendChild(el("p", "lt-note",
      "The drivers' champion was out-paced by their own teammate over the season — qualifying head-to-head and/or race head-to-head (both classified). Same car, so this is the cleanest measure of being beaten by the man in the other garage. Qualifying head-to-head needs 1994+ timing data; earlier rows are race-only. Figures are Phase A's teammate spine joined to each champion."));
    return host;
  }

  // 2) scoring-sensitive titles (flips + ties, kept distinct) --------------
  function systemsWhere(s, pred) {
    return s.invariance.filter(pred).map(function (i) { return i.table; });
  }
  function tiePartners(s, champ) {
    var names = {};
    s.invariance.filter(function (i) { return i.tie; }).forEach(function (i) {
      i.champ.replace(/^TIE:\s*/, "").split(" / ").forEach(function (n) {
        if (n.trim() && n.trim() !== champ) names[n.trim()] = 1;
      });
    });
    return Object.keys(names);
  }
  function scoringBlock(title, sub, rows, kind) {
    var wrap = el("div", "lt-block");
    wrap.appendChild(el("h2", "lt-block-h",
      esc(title) + " <span class='lt-count'>" + rows.length + "</span>"));
    wrap.appendChild(el("p", "lt-block-sub", sub));
    var t = ltable([
      { h: "season", cls: "lt-year" }, { h: "real champion" },
      { h: kind === "flip" ? "would instead win" : "ties at the top with" },
      { h: "under", cls: "lt-sys" },
    ]);
    var tb = t.querySelector("tbody");
    rows.forEach(function (s) {
      var showcase = (s.year === 1988 || s.year === 2008);
      var alts, sys;
      if (kind === "flip") {
        alts = s.flips.join(", ");
        sys = systemsWhere(s, function (i) { return i.changes; });
      } else {
        alts = tiePartners(s, s.champion).join(", ");
        sys = systemsWhere(s, function (i) { return i.tie; });
      }
      var uniqSys = sys.filter(function (v, i) { return sys.indexOf(v) === i; });
      var tr = el("tr" );
      if (showcase) tr.className = "lt-showcase";
      tr.innerHTML = yearCell(s.year) +
        "<td class='lt-name'>" + esc(s.champion) + (showcase ? " <span class='tg tg-star'>showcase</span>" : "") + "</td>" +
        "<td class='lt-name " + (kind === "flip" ? "lt-flip" : "lt-tiealt") + "'>" + esc(alts) + "</td>" +
        "<td class='lt-sys'>" + uniqSys.map(function (x) { return "<span class='chip'>" + esc(x) + "</span>"; }).join("") + "</td>";
      tb.appendChild(rowLink(tr, s.year));
    });
    wrap.appendChild(t);
    return wrap;
  }
  function renderScoring() {
    var host = el("div");
    var flips = seasons.filter(function (s) { return s.anyChange; }).sort(function (a, b) { return a.year - b.year; });
    var ties = seasons.filter(function (s) { return s.hasTie; }).sort(function (a, b) { return a.year - b.year; });
    host.appendChild(scoringBlock(
      "Title would flip", "A different driver wins outright under another historical points table (position points only, all results counting, no fastest-lap point). 1988 is the dropped-scores story — under all-results scoring Prost beats Senna.",
      flips, "flip"));
    host.appendChild(scoringBlock(
      "Tie at the top", "Under another table the championship is level at the top — reported as a genuine tie, NOT a flip. The era's countback tie-break (wins, then places) is noted, not recomputed.",
      ties, "tie"));
    host.appendChild(el("p", "lt-note",
      "Flips (" + flips.length + ") and ties (" + ties.length + ") are kept strictly distinct. A season can appear in both lists when different tables produce different outcomes (e.g. 2008 flips to Massa under the 6-pt-gap systems but ties under the top-5 8-6-4-3-2)."));
    return host;
  }

  // 3) final-race deciders -------------------------------------------------
  function renderFinals() {
    var rows = seasons.filter(function (s) { return s.clinch.wentToFinale; })
      .sort(function (a, b) { return a.clinch.closestMargin - b.clinch.closestMargin || b.year - a.year; });
    var host = el("div");
    var t = ltable([
      { h: "season", cls: "lt-year" }, { h: "deciding race" },
      { h: "champion" }, { h: "runner-up" }, { h: "closest margin", cls: "lt-r" },
    ]);
    var tb = t.querySelector("tbody");
    rows.forEach(function (s) {
      var m = s.clinch.closestMargin;
      var tr = el("tr");
      tr.innerHTML = yearCell(s.year) +
        "<td class='lt-name'>" + esc(s.clinch.race) + "</td>" +
        "<td class='lt-name'>" + esc(s.champion) + "</td>" +
        "<td class='lt-name lt-them'>" + esc(s.runnerUp || "—") + "</td>" +
        "<td class='lt-r'><span class='" + (m <= 1 ? "mg-tight" : "mg") + " num'>" + fmt(m) + "</span></td>";
      tb.appendChild(rowLink(tr, s.year));
    });
    host.appendChild(t);
    host.appendChild(el("p", "lt-note",
      "Every season whose title was mathematically open going into the final round (" + rows.length + " of " + DATA.meta.totals.seasons + "). Sorted by the closest the lead ever got between P1 and P2 across the season (running standings) — lowest first. Margin is in championship points of the era."));
    return host;
  }

  // 4) earliest clinches ---------------------------------------------------
  function renderClinch() {
    var rows = seasons.slice().sort(function (a, b) {
      return b.clinch.racesRemaining - a.clinch.racesRemaining || a.year - b.year;
    });
    var host = el("div");
    var t = ltable([
      { h: "season", cls: "lt-year" }, { h: "champion" },
      { h: "clinched at" }, { h: "races to spare", cls: "lt-r" },
    ]);
    var tb = t.querySelector("tbody");
    rows.forEach(function (s) {
      var rr = s.clinch.racesRemaining;
      var tr = el("tr");
      tr.innerHTML = yearCell(s.year) +
        "<td class='lt-name'>" + esc(s.champion) + "</td>" +
        "<td class='lt-name lt-them'>R" + s.clinch.round + " &middot; " + esc(s.clinch.race) + "</td>" +
        "<td class='lt-r'><span class='" + (rr >= 3 ? "sp-big" : "sp") + " num'>" + rr + "</span></td>";
      tb.appendChild(rowLink(tr, s.year));
    });
    host.appendChild(t);
    host.appendChild(el("p", "lt-note",
      "Most dominant seasons by how early the title was mathematically secured — the counterpoint to the final-race deciders (which sit at 0). Clinch uses the era's real points system and remaining-points math; it is sound (never early), and can read one race conservative pre-1991 due to dropped scores."));
    return host;
  }

  // 5) teammate pace gaps (Phase D, Tier 1 + Tier 2) -----------------------
  var PACE_MIN_N = 5;   // sample-size floor for the ranked leaderboard
  function paceTable(rows, dim) {
    var t = ltable([
      { h: "season", cls: "lt-year" }, { h: "teammates (same car)" },
      { h: "qualifying Δ  T1", cls: "lt-r" }, { h: "n", cls: "lt-r" },
      { h: "race-pace Δ  T2", cls: "lt-r" }, { h: "reliability", cls: "lt-r" },
    ]);
    if (dim) t.className += " lt-dim";
    var tb = t.querySelector("tbody");
    rows.forEach(function (p) {
      var qf = p.quali.median < 0;                     // A faster?
      var fast = qf ? p.aCode : p.bCode, slow = qf ? p.bCode : p.aCode;
      var qd = "<span class='pc-fast'>" + esc(fast) + "</span> <span class='delta num'>&minus;" +
               Math.abs(p.quali.median).toFixed(3) + "s</span> <span class='pc-slow'>" + esc(slow) + "</span>";
      var nCell = "<span class='" + (p.quali.n < PACE_MIN_N ? "n-small" : "num") + "'>" + p.quali.n + "</span>";
      var rd = "<span class='lt-na'>&mdash;</span>", rel = "<span class='lt-na'>&mdash;</span>";
      if (p.race && p.race.median !== null) {
        var rf = p.race.median < 0 ? p.aCode : p.bCode;
        var rweak = p.race.nOk < 3;
        rd = "<span class='pc-fast'>" + esc(rf) + "</span> <span class='delta num" + (rweak ? " delta-weak" : "") + "'>&minus;" +
             Math.abs(p.race.median).toFixed(3) + "</span><span class='unit'>s/lap</span>";
        rel = "<span class='rel " + (rweak ? "rel-low" : "rel-ok") + "'>" + p.race.nOk + " ok</span>" +
              (p.race.nLow ? " <span class='rel rel-low'>" + p.race.nLow + " low</span>" : "");
      } else if (p.race) {
        rd = "<span class='rel rel-low'>low</span>";
        rel = "<span class='rel rel-low'>" + p.race.nLow + " flagged low</span>";
      }
      var tr = el("tr");
      tr.innerHTML = yearCell(p.year) +
        "<td class='lt-name'>" + esc(p.aCode) + " / " + esc(p.bCode) +
          " <span class='lt-them'>" + esc(p.constructor || "") + "</span></td>" +
        "<td class='lt-r'>" + qd + "</td>" +
        "<td class='lt-r'>" + nCell + "</td>" +
        "<td class='lt-r'>" + rd + "</td>" +
        "<td class='lt-r'>" + rel + "</td>";
      tb.appendChild(rowLink(tr, p.year));
    });
    return t;
  }
  function renderPace() {
    var all = DATA.pairings.filter(function (p) { return p.quali; });
    var bymag = function (a, b) { return Math.abs(b.quali.median) - Math.abs(a.quali.median); };
    var solid = all.filter(function (p) { return p.quali.n >= PACE_MIN_N; }).sort(bymag);
    var small = all.filter(function (p) { return p.quali.n < PACE_MIN_N; })
                   .sort(function (a, b) { return b.quali.n - a.quali.n || bymag(a, b); });
    var host = el("div");
    host.appendChild(paceTable(solid, false));
    host.appendChild(el("p", "lt-note",
      "Measured teammate pace gaps (Phase D), most lopsided first. Qualifying Δ (Tier 1, 1994+) is the cleanest comparison — same session, track, car; median time gap, the faster driver carries the negative sign. Race-pace Δ (Tier 2) is a clean green-lap median (lap 1, safety-car, pit and outlier laps removed); only reliable races feed it, low-reliability races are flagged not hidden. The ranked list requires at least " + PACE_MIN_N + " comparison races so a tiny sample cannot top the chart. Every figure is read straight from the validated artifacts — nothing recomputed."));
    if (small.length) {
      host.appendChild(el("h2", "lt-block-h",
        "Small sample <span class='lt-count'>" + small.length + "</span>"));
      host.appendChild(el("p", "lt-block-sub",
        "Fewer than " + PACE_MIN_N + " comparison races — shown for completeness, NOT ranked. A 2-race gap is not a 20-race gap; read these with caution."));
      host.appendChild(paceTable(small, true));
    }
    return host;
  }

  // 6) PACE MODEL (Phase E) — ESTIMATE, visually distinct from measured ------
  function sgnFix(x) { return (x < 0 ? "−" : "+") + Math.abs(x).toFixed(3); }
  function mDriver(id) { return DATA.model.drivers.find(function (d) { return d.id === id; }); }
  function mDriver_byName(n) { return DATA.model.drivers.find(function (d) { return d.name === n; }); }

  function renderModel() {
    var M = DATA.model, host = el("div", "model-wrap");

    // ---- unmissable caveat banner -------------------------------------------
    var banner = el("div", "model-banner");
    banner.innerHTML =
      "<div class='mb-tag'>MODEL · ESTIMATE — not measured fact</div>" +
      "<div class='mb-what'><b>What this is:</b> an estimate of one-lap <b>qualifying pace relative to teammates</b>, " +
      "with the car removed, solved from the 1994+ teammate-delta network. The interval is the point.</div>" +
      "<div class='mb-isnt'><b>What it is NOT:</b> a ranking of greatness, racecraft, wheel-to-wheel ability, " +
      "championships, wet-weather or tyre management. It is modern-era-weighted: <b>qualifying-time data only exists from 1994</b>.</div>" +
      "<div class='mb-era'>Drivers whose prime predates 1994 are under-represented — e.g. <b>Senna</b> appears here from just " +
      "his 3 races in 1994 (±0.64 s, one teammate). An absent or uncertain legend means <i>we cannot measure them</i>, not that they were slow. " +
      "(Conversely, Schumacher <i>is</i> well covered: 1994–2012, 7 teammates.)</div>";
    host.appendChild(banner);

    // ---- ranked CI-band chart (rankable only) -------------------------------
    var rk = M.drivers.filter(function (d) { return d.rankable; })
                      .sort(function (a, b) { return a.rating - b.rating; });
    var lo = Math.min.apply(null, rk.map(function (d) { return d.ciLow; })) - 0.05;
    var hi = Math.max.apply(null, rk.map(function (d) { return d.ciHigh; })) + 0.05;
    var pct = function (x) { return (100 * (x - lo) / (hi - lo)); };

    host.appendChild(el("h2", "model-h", "Estimated qualifying pace — well-connected drivers " +
      "<span class='lt-count'>" + rk.length + "</span>"));
    host.appendChild(el("p", "model-sub",
      "Seconds vs the field mean, car removed — <b>lower = faster</b>. The bar is the 95% confidence interval; " +
      "the tick is the point estimate. <b>Bars that overlap are not confidently separable.</b> " +
      "Only well-connected drivers (≥3 teammates, ≥5 comparisons) are shown here; thin-evidence drivers are below."));

    // axis
    var axis = el("div", "m-axis");
    [-1.0, -0.5, 0.0, 0.5].forEach(function (g) {
      if (g < lo || g > hi) return;
      var t = el("div", "m-axis-t" + (g === 0 ? " m-axis-zero" : ""));
      t.style.left = pct(g) + "%";
      t.innerHTML = "<span>" + (g === 0 ? "field avg" : sgnFix(g).replace(/0+$/, "").replace(/\.$/, "")) + "</span>";
      axis.appendChild(t);
    });
    axis.appendChild(el("div", "m-axis-faster", "◀ faster"));
    host.appendChild(axis);

    rk.forEach(function (d, i) {
      var row = el("div", "mrow");
      var meta = (d.dataFrom === d.dataTo ? d.dataFrom : d.dataFrom + "–" + d.dataTo) +
                 " · " + d.nTeammates + " tm · " + d.nObs + " obs";
      var track = "<div class='mtrack'>" +
        "<div class='mzero' style='left:" + pct(0) + "%'></div>" +
        "<div class='mband' style='left:" + pct(d.ciLow) + "%;width:" + (pct(d.ciHigh) - pct(d.ciLow)) + "%'></div>" +
        "<div class='mtick' style='left:" + pct(d.rating) + "%'></div></div>";
      row.innerHTML =
        "<div class='mname'><span class='mrank'>" + (i + 1) + "</span> " + esc(d.name) +
          " <span class='mmeta'>" + meta + "</span></div>" +
        track +
        "<div class='mval'>" + sgnFix(d.rating) + " <span class='mci'>±" + d.ci95.toFixed(3) + "</span></div>";
      row.tabIndex = 0; row.title = "compare " + d.name;
      host.appendChild(row);
    });

    // ---- pairwise compare (default: the cross-era tie) ----------------------
    host.appendChild(el("h2", "model-h", "Compare two drivers"));
    host.appendChild(el("p", "model-sub",
      "Pairwise uncertainty uses the <b>effective resistance</b> of the teammate chain linking them: " +
      "direct, same-era teammates compare tightly; cross-era pairs rest on a long fragile chain and read as a <b>statistical tie</b>."));
    var cmp = el("div", "mcompare");
    var optList = rk.slice().sort(function (a, b) { return a.name.localeCompare(b.name); });
    var opts = function (sel) {
      return optList.map(function (d) {
        return "<option value='" + d.id + "'" + (d.id === sel ? " selected" : "") + ">" + esc(d.name) + "</option>";
      }).join("");
    };
    var SCH = (mDriver_byName("Michael Schumacher") || {}).id;
    var VER = (mDriver_byName("Max Verstappen") || {}).id;
    cmp.innerHTML = "<div class='mc-pick'><select id='cmpA'>" + opts(SCH) + "</select>" +
      "<span class='mc-vs'>vs</span><select id='cmpB'>" + opts(VER) + "</select></div>" +
      "<div id='cmpOut'></div>";
    host.appendChild(cmp);

    function renderCompare() {
      var a = mDriver(+cmp.querySelector("#cmpA").value);
      var b = mDriver(+cmp.querySelector("#cmpB").value);
      var outEl = cmp.querySelector("#cmpOut");
      if (!a || !b || a.id === b.id) { outEl.innerHTML = "<div class='mc-note'>pick two different drivers</div>"; return; }
      var key = Math.min(a.id, b.id) + "_" + Math.max(a.id, b.id);
      var ci = M.pairwise[key];
      var gap = Math.abs(a.rating - b.rating);
      var faster = a.rating < b.rating ? a : b;
      var tie = (ci == null) || (gap < ci);
      // shared mini scale
      var clo = Math.min(a.ciLow, b.ciLow) - 0.05, chi = Math.max(a.ciHigh, b.ciHigh) + 0.05;
      var p = function (x) { return 100 * (x - clo) / (chi - clo); };
      function bar(d, cls) {
        return "<div class='mrow mc-row'><div class='mname'>" + esc(d.code || d.name) +
          " <span class='mmeta'>" + d.dataFrom + "–" + d.dataTo + "</span></div>" +
          "<div class='mtrack'><div class='mband " + cls + "' style='left:" + p(d.ciLow) + "%;width:" +
          (p(d.ciHigh) - p(d.ciLow)) + "%'></div><div class='mtick' style='left:" + p(d.rating) + "%'></div></div>" +
          "<div class='mval'>" + sgnFix(d.rating) + " <span class='mci'>±" + d.ci95.toFixed(3) + "</span></div></div>";
      }
      var verdict = tie
        ? "<span class='mc-tie'>STATISTICAL TIE</span> — the " + gap.toFixed(3) +
          " s gap is within the <b>±" + (ci != null ? ci.toFixed(3) : "—") +
          " s</b> uncertainty of this comparison. The model cannot confidently separate them."
        : "<span class='mc-sep'>" + esc(faster.name) + " estimated faster</span> by " + gap.toFixed(3) +
          " s — just beyond the ±" + ci.toFixed(3) + " s uncertainty. Still an estimate, not a verdict.";
      outEl.innerHTML = bar(a, "mc-a") + bar(b, "mc-b") +
        "<div class='mc-verdict'>" + verdict + "</div>";
    }
    cmp.querySelector("#cmpA").addEventListener("change", renderCompare);
    cmp.querySelector("#cmpB").addEventListener("change", renderCompare);
    renderCompare();

    // ---- thin-evidence drivers ----------------------------------------------
    var thin = M.drivers.filter(function (d) { return !d.rankable && d.component === "giant"; })
                        .sort(function (a, b) { return a.rating - b.rating; });   // fastest-looking first
    host.appendChild(el("h2", "model-h", "Thin evidence — wide uncertainty " +
      "<span class='lt-count'>" + thin.length + "</span>"));
    host.appendChild(el("p", "model-sub",
      "Few teammates, few comparisons, or a single old season — <b>not confidently rankable</b>. Shown by " +
      "fastest point estimate first to make the danger obvious: e.g. <b>Senna</b> tops it on paper, but the " +
      "<b>±0.64 s</b> interval (3 races, 1994) means the point estimate can't be trusted. Wide bars are the warning."));
    var tt = el("table", "lt lt-dim");
    tt.innerHTML = "<thead><tr><th>driver</th><th>data</th><th class='lt-r'>estimate</th>" +
      "<th class='lt-r'>95% CI</th><th class='lt-r'>teammates</th></tr></thead>";
    var ttb = el("tbody");
    thin.slice(0, 30).forEach(function (d) {
      var tr = el("tr");
      tr.innerHTML = "<td class='lt-name'>" + esc(d.name) + "</td>" +
        "<td class='lt-them num'>" + (d.dataFrom === d.dataTo ? d.dataFrom : d.dataFrom + "–" + d.dataTo) + "</td>" +
        "<td class='lt-r num'>" + sgnFix(d.rating) + "</td>" +
        "<td class='lt-r'><span class='mci-wide'>±" + (d.ci95 != null ? d.ci95.toFixed(3) : "—") + "</span></td>" +
        "<td class='lt-r num'>" + d.nTeammates + "</td>";
      ttb.appendChild(tr);
    });
    tt.appendChild(ttb); host.appendChild(tt);

    // ---- how it works / limitations -----------------------------------------
    var how = el("details", "model-how");
    how.innerHTML =
      "<summary>How this works &amp; its limitations</summary>" +
      "<div class='mh-body'>" +
      "<p><b>Method.</b> The only car-controlled comparison is teammates (same car, same season). Each Phase&nbsp;D Tier-1 " +
      "qualifying delta becomes an edge in a network of drivers; we solve all edges at once by weighted least squares " +
      "(a chained comparison: A&gt;B, B&gt;C ⇒ A&gt;C) for the driver-pace numbers that best explain every teammate gap. " +
      "Inputs are read from the validated Phase&nbsp;D artifacts — nothing here is re-measured.</p>" +
      "<p><b>Why cross-era is uncertain.</b> Two drivers who never shared a garage are only linked through a chain of " +
      "teammates-of-teammates. Confidence collapses along long, weak chains (formally, the <i>effective resistance</i> of the " +
      "network path). That is why a 1990s–vs–2020s comparison shows a wide interval and usually a statistical tie.</p>" +
      "<p><b>What the interval means.</b> A 95% confidence range from propagating the measurement noise through the network. " +
      "The career-average simplification leaves real scatter (σ̂²≈" + M.meta.sigma2 + "), and we widen every interval " +
      "to reflect it. Overlapping intervals = not confidently separable.</p>" +
      "<p><b>Scope.</b> " + M.meta.nDrivers + " drivers, " + M.meta.nEdges + " teammate-delta edges, " +
      M.meta.eraFrom + "–" + M.meta.eraTo + ". Reconstruction median residual " + M.meta.medianResidual + " s. " +
      "This estimates qualifying pace only — not racecraft, not greatness.</p>" +
      "</div>";
    host.appendChild(how);
    return host;
  }

  var VIEWS = {
    "#/beaten":  { tab: "#/beaten",  title: "Champions beaten by their teammate",
                   sub: "The 2016 Rosberg anomaly, generalised across 75 seasons.", render: renderBeaten },
    "#/scoring": { tab: "#/scoring", title: "Scoring-sensitive titles",
                   sub: "Where the points system, not the driving, decides the champion.", render: renderScoring },
    "#/finals":  { tab: "#/finals",  title: "Final-race deciders",
                   sub: "Titles still mathematically open at the last round.", render: renderFinals },
    "#/clinch":  { tab: "#/clinch",  title: "Earliest clinches",
                   sub: "Titles secured with the most races to spare.", render: renderClinch },
    "#/pace":    { tab: "#/pace",    title: "Teammate pace gaps",
                   sub: "Tenths-level measured deltas, same car (Phase D). Tiers visible.", render: renderPace },
    "#/model":   { tab: "#/model",   title: "Driver pace model",
                   sub: "ESTIMATE — car-normalised qualifying pace, with uncertainty (Phase E).",
                   render: renderModel, model: true },
  };

  /* ====================================================================== */
  /*  ROUTER                                                                */
  /* ====================================================================== */
  function setActiveTab(route) {
    var tabs = document.querySelectorAll("#tabs .tab");
    for (var i = 0; i < tabs.length; i++) {
      tabs[i].classList.toggle("active", tabs[i].getAttribute("data-route") === route);
    }
  }
  function showSeasonView(show) {
    $("view-season").hidden = !show;
    $("view-list").hidden = show;
  }

  function route() {
    var h = location.hash || "#/";
    // legacy bare-year hash (e.g. #2008)
    var bare = h.match(/^#(\d{4})$/);
    if (bare) { location.replace("#/s/" + bare[1]); return; }

    var sm = h.match(/^#\/s\/(\d{4})$/);
    if (VIEWS[h]) {
      var v = VIEWS[h];
      showSeasonView(false);
      setActiveTab(v.tab);
      $("list-title").textContent = v.title;
      $("list-sub").textContent = v.sub;
      var body = $("list-body"); body.innerHTML = "";
      body.appendChild(v.render());
      document.body.classList.toggle("is-model", !!v.model);   // distinct treatment for the estimate view
      $("ro-gap").textContent = v.model ? "MODEL · EST" : h.replace("#/", "").toUpperCase();
      window.scrollTo(0, 0);
    } else {
      var yr = sm ? +sm[1] : (byYear[+(h.replace(/[^\d]/g, ""))] ? +(h.replace(/[^\d]/g, "")) : 2008);
      showSeasonView(true);
      setActiveTab("#/");
      document.body.classList.remove("is-model");
      renderSeason(yr);
      if (sm) window.scrollTo(0, 0);
    }
  }

  /* ====================================================================== */
  /*  INIT                                                                  */
  /* ====================================================================== */
  function init() {
    tower();
    var sel = $("season");
    years.slice().reverse().forEach(function (y) {
      sel.appendChild(el("option", null, y)).value = y;
    });
    sel.addEventListener("change", function () { location.hash = "#/s/" + sel.value; });
    $("prev").addEventListener("click", function () {
      var i = years.indexOf(+sel.value); if (i > 0) location.hash = "#/s/" + years[i - 1];
    });
    $("next").addEventListener("click", function () {
      var i = years.indexOf(+sel.value); if (i < years.length - 1) location.hash = "#/s/" + years[i + 1];
    });
    document.addEventListener("keydown", function (e) {
      if ($("view-season").hidden) return;             // arrows only drive the dossier
      if (e.key === "ArrowLeft") $("prev").click();
      if (e.key === "ArrowRight") $("next").click();
    });
    window.addEventListener("hashchange", route);
    route();
  }

  init();
})();
